"""C code generator for designed IIR filters.

Emits a header and a source file that implement the filter as a cascade of
second order sections:

* float / double: transposed direct form II (good numerical behaviour in floating point)
* fixed16 / fixed32: direct form I with a 64 bit accumulator, rounding and saturation.
  The arithmetic is bit-exact to fdcore.fixed_filter(), so the GUI shows exactly
  what the target computes.
"""

from __future__ import annotations

import datetime
import re

import numpy as np

from fdcore import Design, FixedPoint

ARITHMETICS = {
    "float": "32 bit floating point (float)",
    "double": "64 bit floating point (double)",
    "fixed32": "32 bit fixed point (int32_t data/coefficients, int64_t accumulator)",
    "fixed16": "16 bit fixed point (int16_t data/coefficients, int64_t accumulator)",
}


def c_identifier(name: str) -> str:
    ident = re.sub(r"[^0-9a-zA-Z_]", "_", name.strip()).lower() or "iir_filter"
    if ident[0].isdigit():
        ident = "f_" + ident
    return ident


def _spec_comment(d: Design) -> str:
    s = d.spec
    n = 2 if s.two_edges else 1
    edges = lambda v: ", ".join(f"{x:g}" for x in v[:n])
    att = lambda v: ", ".join(f"{x:.2f}" for x in v)
    return (
        f" * Filter      : {s.characteristic} {s.type}, order {d.digital_order}, "
        f"{len(d.sos)} section(s)\n"
        f" * Sample rate : {s.fs:g} Hz\n"
        f" * Passband    : {edges(s.fpass)} Hz, max. {s.ap:g} dB attenuation (achieved {att(d.att_pass)} dB)\n"
        f" * Stopband    : {edges(s.fstop)} Hz, min. {s.as_:g} dB attenuation (achieved {att(d.att_stop)} dB)\n"
    )


def generate(d: Design, name: str, arithmetic: str, sos: np.ndarray,
             fixed: FixedPoint | None = None) -> tuple[str, str, str, str]:
    """Returns (header_filename, header, source_filename, source).

    sos is the (optionally section-scaled) cascade; for fixed point, `fixed`
    holds its quantized coefficients.
    """
    ident = c_identifier(name)
    up = ident.upper()
    n = len(sos)
    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    head = (
        f"/*\n * {ident} - IIR filter generated by FilterDesign GUI ({stamp})\n *\n"
        f"{_spec_comment(d)}"
        f" * Arithmetic  : {ARITHMETICS[arithmetic]}\n"
    )

    if arithmetic in ("float", "double"):
        t = arithmetic
        suffix = "f" if t == "float" else ""
        fmt = "{:.9g}" if t == "float" else "{:.17g}"

        def lit(v: float) -> str:
            s = fmt.format(v)
            if not re.search(r"[.eEn]", s):
                s += ".0"
            return s + suffix

        header = head + (
            f" *\n * Structure   : {n} second order section(s), transposed direct form II\n"
            " *               y = b0*x + s0;  s0 = b1*x - a1*y + s1;  s1 = b2*x - a2*y\n */\n\n"
            f"#ifndef {up}_H\n#define {up}_H\n\n#include <stddef.h>\n\n"
            f"#define {up}_NUM_SECTIONS {n}\n#define {up}_SAMPLE_RATE {d.spec.fs:g}\n\n"
            f"typedef struct {{\n    {t} s[{up}_NUM_SECTIONS][2];\n}} {ident}_state_t;\n\n"
            f"/* Clears the filter state. */\n"
            f"void {ident}_init({ident}_state_t *st);\n\n"
            f"/* Filters one sample. */\n"
            f"{t} {ident}_process({ident}_state_t *st, {t} x);\n\n"
            f"/* Filters n samples; in and out may point to the same buffer. */\n"
            f"void {ident}_process_block({ident}_state_t *st, const {t} *in, {t} *out, size_t n);\n\n"
            f"#endif /* {up}_H */\n"
        )
        rows = ",\n".join(
            "    {" + ", ".join(lit(v) for v in (r[0], r[1], r[2], r[4], r[5])) + "}"
            for r in sos)
        source = head + " */\n\n" + (
            f"#include <string.h>\n\n#include \"{ident}.h\"\n\n"
            f"/* per section: b0, b1, b2, a1, a2  (a0 = 1) */\n"
            f"static const {t} {ident}_coeffs[{up}_NUM_SECTIONS][5] = {{\n{rows}\n}};\n\n"
            f"void {ident}_init({ident}_state_t *st)\n{{\n    memset(st, 0, sizeof *st);\n}}\n\n"
            f"{t} {ident}_process({ident}_state_t *st, {t} x)\n{{\n"
            f"    int k;\n\n"
            f"    for (k = 0; k < {up}_NUM_SECTIONS; k++) {{\n"
            f"        const {t} *c = {ident}_coeffs[k];\n"
            f"        {t} *s = st->s[k];\n"
            f"        {t} y = c[0] * x + s[0];\n\n"
            f"        s[0] = c[1] * x - c[3] * y + s[1];\n"
            f"        s[1] = c[2] * x - c[4] * y;\n"
            f"        x = y;\n"
            f"    }}\n    return x;\n}}\n\n"
            f"void {ident}_process_block({ident}_state_t *st, const {t} *in, {t} *out, size_t n)\n{{\n"
            f"    size_t i;\n\n"
            f"    for (i = 0; i < n; i++) {{\n        out[i] = {ident}_process(st, in[i]);\n    }}\n}}\n"
        )
        return f"{ident}.h", header, f"{ident}.c", source

    # ---------------------------------------------------------------- fixed point
    assert fixed is not None
    w = fixed.word
    t = f"int{w}_t"
    vmax, vmin = (1 << (w - 1)) - 1, -(1 << (w - 1))
    vmin_c = f"(-{vmax} - 1)" if w == 32 else str(vmin)
    header = head + (
        f" *\n * Structure   : {n} second order section(s), direct form I, 64 bit accumulator\n"
        f" *               y = sat((b0*x + b1*x1 + b2*x2 - a1*y1 - a2*y2 + 2^(F-1)) >> F)\n"
        f" * Coefficients: Q{w - 1 - fixed.frac}.{fixed.frac} in {t} "
        f"(F = {up}_FRAC_BITS = {fixed.frac}, range +/-{fixed.coeff_range:g})\n"
        f" * Samples     : {t}, any scaling (e.g. Q{w - 1}); input and output use the same scaling\n"
        f" * Note        : relies on an arithmetic right shift of negative int64_t values\n"
        f" *               (true for GCC, Clang, XC16, XC32, IAR, Keil)\n */\n\n"
        f"#ifndef {up}_H\n#define {up}_H\n\n#include <stddef.h>\n#include <stdint.h>\n\n"
        f"#define {up}_NUM_SECTIONS {n}\n#define {up}_FRAC_BITS {fixed.frac}\n"
        f"#define {up}_SAMPLE_RATE {d.spec.fs:g}\n\n"
        f"typedef struct {{\n    {t} x[{up}_NUM_SECTIONS][2];  /* x[n-1], x[n-2] */\n"
        f"    {t} y[{up}_NUM_SECTIONS][2];  /* y[n-1], y[n-2] */\n}} {ident}_state_t;\n\n"
        f"/* Clears the filter state. */\n"
        f"void {ident}_init({ident}_state_t *st);\n\n"
        f"/* Filters one sample. */\n"
        f"{t} {ident}_process({ident}_state_t *st, {t} x);\n\n"
        f"/* Filters n samples; in and out may point to the same buffer. */\n"
        f"void {ident}_process_block({ident}_state_t *st, const {t} *in, {t} *out, size_t n);\n\n"
        f"#endif /* {up}_H */\n"
    )
    rows = []
    for q, r in zip(fixed.coeffs, sos):
        ints = ", ".join(f"{int(v):>{12 if w == 32 else 7}d}" for v in q)
        flt = ", ".join(f"{v:.9g}" for v in (r[0], r[1], r[2], r[4], r[5]))
        rows.append(f"    {{{ints}}}  /* {flt} */")
    source = head + " */\n\n" + (
        f"#include <string.h>\n\n#include \"{ident}.h\"\n\n"
        f"#define {up}_MAX ({vmax})\n#define {up}_MIN {vmin_c}\n"
        f"#define {up}_ROUND (((int64_t)1 << {up}_FRAC_BITS) >> 1)\n\n"
        f"/* per section: b0, b1, b2, a1, a2  (a0 = 1), Q{fixed.frac} */\n"
        f"static const {t} {ident}_coeffs[{up}_NUM_SECTIONS][5] = {{\n" + ",\n".join(rows) + "\n};\n\n"
        f"void {ident}_init({ident}_state_t *st)\n{{\n    memset(st, 0, sizeof *st);\n}}\n\n"
        f"{t} {ident}_process({ident}_state_t *st, {t} x)\n{{\n"
        f"    int k;\n\n"
        f"    for (k = 0; k < {up}_NUM_SECTIONS; k++) {{\n"
        f"        const {t} *c = {ident}_coeffs[k];\n"
        f"        {t} *xs = st->x[k];\n"
        f"        {t} *ys = st->y[k];\n"
        f"        int64_t acc = (int64_t)c[0] * x\n"
        f"                    + (int64_t)c[1] * xs[0]\n"
        f"                    + (int64_t)c[2] * xs[1]\n"
        f"                    - (int64_t)c[3] * ys[0]\n"
        f"                    - (int64_t)c[4] * ys[1];\n\n"
        f"        acc = (acc + {up}_ROUND) >> {up}_FRAC_BITS;\n"
        f"        if (acc > {up}_MAX) {{\n            acc = {up}_MAX;\n"
        f"        }} else if (acc < {up}_MIN) {{\n            acc = {up}_MIN;\n        }}\n"
        f"        xs[1] = xs[0];\n        xs[0] = x;\n"
        f"        ys[1] = ys[0];\n        ys[0] = ({t})acc;\n"
        f"        x = ({t})acc;\n"
        f"    }}\n    return x;\n}}\n\n"
        f"void {ident}_process_block({ident}_state_t *st, const {t} *in, {t} *out, size_t n)\n{{\n"
        f"    size_t i;\n\n"
        f"    for (i = 0; i < n; i++) {{\n        out[i] = {ident}_process(st, in[i]);\n    }}\n}}\n"
    )
    return f"{ident}.h", header, f"{ident}.c", source
