"""Tests the generated C implementations: compile, run with a test signal, compare.

For every arithmetic (float, double, fixed32, fixed16) the generated filter and its
test bench (codegen.generate_testbench) are compiled with the host C compiler and run
with a test signal. The output is compared with

* the double precision reference (scipy.signal.sosfilt of the same cascade), and
* for fixed point additionally with the bit-exact Python model fdcore.fixed_filter.

A second run with an impulse gives the measured frequency response of the C code.
"""

from __future__ import annotations

import hashlib
import io
import os
import shutil
import subprocess
import tempfile
import zipfile
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
from scipy import signal

import codegen
import fdcore

SIGNALS = {
    "impulse": "Impulse",
    "step": "Step",
    "sine": "Sine (f1)",
    "chirp": "Chirp (f1 → f2)",
    "noise": "White noise",
    "multitone": "Multitone (f1, f2)",
}


CACHE_DIR = Path(tempfile.gettempdir()) / "fdesign_ctest"


class CTestError(Exception):
    pass


def find_compiler(cc: str | None = None) -> str | None:
    """Returns the path of the C compiler (argument, $CC, gcc, cc, clang) or None."""
    for c in [cc, os.environ.get("CC"), "gcc", "cc", "clang"]:
        if c:
            p = shutil.which(c)
            if p:
                return p
    return None


def make_signal(kind: str, n: int, fs: float, f1: float, f2: float, seed: int = 1) -> np.ndarray:
    """Test signal in the range [-1, 1]."""
    t = np.arange(n) / fs
    if kind == "impulse":
        x = np.zeros(n)
        x[0] = 1.0
    elif kind == "step":
        x = np.ones(n)
    elif kind == "sine":
        x = np.sin(2 * np.pi * f1 * t)
    elif kind == "chirp":
        x = signal.chirp(t, f0=f1, t1=t[-1] if n > 1 else 1.0, f1=f2, method="linear")
    elif kind == "noise":
        x = np.random.default_rng(seed).uniform(-1.0, 1.0, n)
    elif kind == "multitone":
        x = 0.5 * np.sin(2 * np.pi * f1 * t) + 0.5 * np.sin(2 * np.pi * f2 * t)
    else:
        raise ValueError(f"unknown signal {kind}")
    return x


@dataclass
class ImplResult:
    arith: str
    ok: bool = False                  # compiled and ran
    message: str = ""                 # compiler/runtime error
    x: np.ndarray | None = None       # input as seen by the implementation (normalized, quantized)
    y: np.ndarray | None = None       # output of the C code (normalized: 1.0 = full scale)
    ref: np.ndarray | None = None     # double reference for the same input
    max_err: float = float("nan")
    rms_err: float = float("nan")
    snr_db: float = float("nan")
    lsb: float | None = None          # fixed point: 1 LSB in normalized units
    bit_exact: bool | None = None     # fixed point: identical to the Python model
    saturations: int | None = None    # fixed point: saturations in the run
    frac: int | None = None
    testbench_pass: bool | None = None
    testbench_msg: str = ""
    f_meas: np.ndarray | None = None  # frequency grid of the measured response
    h_meas: np.ndarray | None = None  # measured magnitude response (linear)
    compile_cmd: str = ""


@dataclass
class TestRun:
    signal: str
    n: int
    amplitude: float
    results: list[ImplResult] = field(default_factory=list)
    f_design: np.ndarray | None = None
    h_design: np.ndarray | None = None


def _write_values(path: Path, values: np.ndarray, integer: bool) -> None:
    if integer:
        path.write_text("\n".join(str(int(v)) for v in values) + "\n")
    else:
        path.write_text("\n".join(repr(float(v)) for v in values) + "\n")


def _build(d: fdcore.Design, arith: str, sos: np.ndarray, fixed, cc: str) -> tuple[Path, str]:
    """Compiles filter + test bench; identical sources are compiled only once (cache)."""
    name = "filt"
    hname, header, cname, source = codegen.generate(d, name, arith, sos, fixed)
    tname, tsrc = codegen.generate_testbench(name, arith)
    # the time stamp in the header comment must not defeat the cache
    strip = lambda txt: "\n".join(l for l in txt.splitlines() if "generated by FilterDesign GUI" not in l)
    key = hashlib.sha1("\0".join([cc, strip(header), strip(source), tsrc]).encode()).hexdigest()[:16]
    work = CACHE_DIR / key
    exe = work / ("filt_test.exe" if os.name == "nt" else "filt_test")
    cmd = [cc, "-std=c99", "-O2", "-Wall", "-Wextra", "-o", exe.name, tname, cname, "-lm"]
    shown = " ".join([Path(cc).name] + cmd[1:])
    if exe.exists():
        return exe, shown + "  (cached)"
    work.mkdir(parents=True, exist_ok=True)
    (work / hname).write_text(header)
    (work / cname).write_text(source)
    (work / tname).write_text(tsrc)
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=120, cwd=work)
    if r.returncode != 0 or not exe.exists():
        raise CTestError("compilation failed:\n" + (r.stderr or r.stdout).strip())
    warnings = (r.stderr or "").strip()
    return exe, shown + (f"\n{warnings}" if warnings else "")


def _run(exe: Path, workdir: Path, values: np.ndarray, integer: bool, expected: np.ndarray | None = None,
         tag: str = "in") -> tuple[np.ndarray, int, str]:
    inp = workdir / f"{tag}.txt"
    _write_values(inp, values, integer)
    args = [str(exe), str(inp)]
    if expected is not None:
        exp = workdir / f"{tag}_expected.txt"
        _write_values(exp, expected, integer)
        args.append(str(exp))
    r = subprocess.run(args, capture_output=True, text=True, timeout=120)
    if r.returncode not in (0, 1):
        raise CTestError(f"test program failed (exit {r.returncode}): {r.stderr.strip()}")
    out = r.stdout.split()
    if len(out) != len(values):
        raise CTestError(f"test program returned {len(out)} samples instead of {len(values)}")
    y = np.array([int(v) for v in out], dtype=np.int64) if integer else np.array([float(v) for v in out])
    return y, r.returncode, r.stderr.strip()


def test_implementation(d: fdcore.Design, arith: str, x: np.ndarray, amplitude: float, cc: str,
                        scaled: bool = True, frac: int | None = None, n_impulse: int = 8192) -> ImplResult:
    res = ImplResult(arith=arith)
    sos, fixed, _ = fdcore.implement(d.sos, d.spec.fs, arith, scaled, frac)
    integer = fixed is not None
    with tempfile.TemporaryDirectory(prefix="fdtest_") as td:
        work = Path(td)
        try:
            exe, res.compile_cmd = _build(d, arith, sos, fixed, cc)

            # ---- test signal
            if integer:
                full = (1 << (fixed.word - 1)) - 1
                xi = np.clip(np.round(amplitude * x * full), -full - 1, full).astype(np.int64)
                model, sat = fdcore.fixed_filter(fixed, xi)
                yi, rc, msg = _run(exe, work, xi, True, expected=model)
                res.bit_exact = bool(np.array_equal(yi, model))
                res.saturations = sat
                res.frac = fixed.frac
                res.lsb = 1.0 / full
                res.x = xi / full
                res.y = yi / full
            else:
                xa = amplitude * x
                if arith == "float":
                    xa = xa.astype(np.float32).astype(float)
                ref_exp = signal.sosfilt(sos, xa)
                yv, rc, msg = _run(exe, work, xa, False, expected=ref_exp)
                res.x = xa
                res.y = yv
            res.testbench_pass = rc == 0
            res.testbench_msg = msg
            res.ref = signal.sosfilt(sos, res.x)
            err = res.y - res.ref
            res.max_err = float(np.max(np.abs(err)))
            res.rms_err = float(np.sqrt(np.mean(err ** 2)))
            p_ref = float(np.mean(res.ref ** 2))
            res.snr_db = (10 * np.log10(p_ref / np.mean(err ** 2)) if np.mean(err ** 2) > 0 and p_ref > 0
                          else float("inf"))

            # ---- measured frequency response from the impulse response
            if integer:
                imp = (1 << (fixed.word - 1)) // 2
                xi = np.zeros(n_impulse, dtype=np.int64)
                xi[0] = imp
                hi, _, _ = _run(exe, work, xi, True, tag="impulse")
                h = hi / imp
            else:
                xv = np.zeros(n_impulse)
                xv[0] = 1.0
                h, _, _ = _run(exe, work, xv, False, tag="impulse")
            nfft = max(8192, 1 << int(np.ceil(np.log2(n_impulse))))
            res.h_meas = np.abs(np.fft.rfft(h, nfft))
            res.f_meas = np.fft.rfftfreq(nfft, 1.0 / d.spec.fs)
            res.ok = True
        except (CTestError, subprocess.TimeoutExpired, OSError) as e:
            res.message = str(e)
    return res


def run_tests(d: fdcore.Design, ariths: list[str], kind: str, n: int, amplitude: float,
              f1: float, f2: float, cc: str, scaled: bool = True,
              frac_override: dict[str, int] | None = None) -> TestRun:
    """Runs the test for all requested arithmetics (blocking; call from a worker thread)."""
    x = make_signal(kind, n, d.spec.fs, f1, f2)
    run = TestRun(signal=kind, n=n, amplitude=amplitude)
    n_imp = int(min(max(2 * fdcore.settle_length(d.sos), 4096), 1 << 16))
    with ThreadPoolExecutor(max_workers=max(1, len(ariths))) as pool:
        futures = [pool.submit(test_implementation, d, a, x, amplitude, cc, scaled,
                               (frac_override or {}).get(a), n_imp) for a in ariths]
        run.results = [f.result() for f in futures]
    f = np.fft.rfftfreq(8192, 1.0 / d.spec.fs)
    ok = [r for r in run.results if r.ok]
    run.f_design = ok[0].f_meas if ok else f
    run.h_design = np.abs(fdcore.response(d.sos, run.f_design, d.spec.fs))
    return run


def testbench_zip(d: fdcore.Design, name: str, arith: str, kind: str, n: int, amplitude: float,
                  f1: float, f2: float, scaled: bool = True, frac: int | None = None) -> bytes:
    """Zip archive with filter, test bench, Makefile, input and expected output."""
    sos, fixed, _ = fdcore.implement(d.sos, d.spec.fs, arith, scaled, frac)
    hname, header, cname, source = codegen.generate(d, name, arith, sos, fixed)
    tname, tsrc = codegen.generate_testbench(name, arith)
    x = make_signal(kind, n, d.spec.fs, f1, f2)
    if fixed is not None:
        full = (1 << (fixed.word - 1)) - 1
        xi = np.clip(np.round(amplitude * x * full), -full - 1, full).astype(np.int64)
        expected, _ = fdcore.fixed_filter(fixed, xi)
        inp = "\n".join(str(int(v)) for v in xi) + "\n"
        exp = "\n".join(str(int(v)) for v in expected) + "\n"
    else:
        xa = amplitude * x
        if arith == "float":
            xa = xa.astype(np.float32).astype(float)
        inp = "\n".join(repr(float(v)) for v in xa) + "\n"
        exp = "\n".join(repr(float(v)) for v in signal.sosfilt(sos, xa)) + "\n"
    readme = (
        f"Test bench for {codegen.c_identifier(name)} ({codegen.ARITHMETICS[arith]})\n\n"
        f"Signal   : {SIGNALS[kind]}, {n} samples, amplitude {amplitude:g} of full scale\n"
        f"Build    : make            (or: gcc -std=c99 -O2 -o test {tname} {cname} -lm)\n"
        f"Run      : make test       (or: ./test input.txt expected.txt > output.txt)\n\n"
        "input.txt     test signal, one sample per line\n"
        "expected.txt  expected output (fixed point: bit-exact model, float/double: double reference)\n"
        "The program prints PASS or FAIL and returns 0 or 1.\n"
    )
    mem = io.BytesIO()
    with zipfile.ZipFile(mem, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr(hname, header)
        z.writestr(cname, source)
        z.writestr(tname, tsrc)
        z.writestr("Makefile", codegen.generate_makefile(name))
        z.writestr("input.txt", inp)
        z.writestr("expected.txt", exp)
        z.writestr("README.txt", readme)
    return mem.getvalue()
